import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";
import PrinterMonitor from "./components/PrinterMonitor";
import PaymentWatcher from "./components/PaymentWatcher";
import ActivationGuard from "./components/ActivationGuard";

import { getBrandingSettings } from "./actions/settings";
import ThemeRegistry from "./components/ThemeRegistry";

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getBrandingSettings();
  const themeColor = settings?.brandingThemeColor || "orange";

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
      >
        <ThemeRegistry color={themeColor}>
          <ActivationGuard>
            <PaymentWatcher />
            {children}
            <PrinterMonitor />
          </ActivationGuard>
        </ThemeRegistry>
      </body>
    </html>
  );
}
