import fs from 'fs';
import path from 'path';

/**
 * Retrieves the Mercado Pago Access Token.
 * It first checks for a local config.json file (generated by Electron) in the AppData folder.
 * If not found or invalid, it falls back to the environment variable MP_ACCESS_TOKEN.
 */
export async function getMpAccessToken(): Promise<string> {
    const envToken = process.env.MP_ACCESS_TOKEN || '';

    // In production/Electron, we want to look for the config.json saved by electron-store.
    // electron-store saves to app.getPath('userData').
    // On Windows, this is usually %APPDATA%\mifoto-hotfolder\

    // We only attempt this check if running on the server side (Next.js API routes)
    if (typeof window === 'undefined') {
        try {
            // We need to resolve the AppData path. 
            // process.env.APPDATA is available on Windows.
            const appData = process.env.APPDATA;
            if (appData) {
                const configPath = path.join(appData, 'mifoto-hotfolder', 'config.json');

                if (fs.existsSync(configPath)) {
                    const fileContent = fs.readFileSync(configPath, 'utf-8');
                    const config = JSON.parse(fileContent);

                    if (config && config.mpAccessToken) {
                        //  console.log('[Config] Using Dynamic MP Access Token from local config.');
                        return config.mpAccessToken;
                    }
                }
            }
        } catch (error) {
            console.warn('[Config] Failed to read local config.json, falling back to ENV.', error);
        }
    }

    return envToken;
}
